from ._helpers import E8, csv

def test_controlled_actions():
    allowed = {"NO_ACTION","WATCH","INCREASE_MONITORING_FREQUENCY","DATA_FIX_REQUIRED","DOCUMENTATION_UPDATE","LIMITATION_UPDATE","POLICY_REVIEW","CALIBRATION_REVIEW","MODEL_RECALIBRATION_CANDIDATE","MODEL_REDEVELOPMENT_CANDIDATE","MODEL_USE_RESTRICTION","BLOCK_ANALYTICAL_USE"}
    assert set(csv(E8 / "action_register.csv").action_type) <= allowed
