"""Export sanitized, aggregate-only B6-B9 reports and public evidence."""
from __future__ import annotations
import argparse, csv, json
from pathlib import Path

def read_json(path): return json.loads(path.read_text(encoding='utf-8'))
def read_csv(path):
    with path.open(encoding='utf-8', newline='') as f: return list(csv.DictReader(f))
def pct(v): return f"{float(v) * 100:.2f}%"
def money(v): return f"${float(v):,.0f}"
def write(path, text): path.parent.mkdir(parents=True, exist_ok=True); path.write_text(text.strip()+'\n', encoding='utf-8')

def main():
    p=argparse.ArgumentParser(); p.add_argument('--repo-root',type=Path,default=Path(__file__).resolve().parents[1]); a=p.parse_args(); r=a.repo_root
    b6=read_json(r/'outputs/b6/portfolio_kpis.json'); b6t=read_json(r/'outputs/b6/b6_test_results.json'); b7t=read_json(r/'outputs/b7/b7_test_results.json'); b8=read_json(r/'outputs/b8/b8_summary.json'); b8t=read_json(r/'outputs/b8/b8_test_results.json'); b9=read_json(r/'outputs/b9/b9_summary.json'); b9t=read_json(r/'outputs/b9/b9_test_results.json')
    seg=read_csv(r/'outputs/b7/segment_risk.csv'); conc=read_csv(r/'outputs/b8/risk_concentration.csv'); annual=read_csv(r/'outputs/b9/vintage_annual.csv'); splits=read_csv(r/'outputs/b9/vintage_split.csv')
    headline=sorted([x for x in seg if x['primary_segment']=='True'],key=lambda x: float(x['bad_rate']),reverse=True)[:8]
    material=sorted([x for x in conc if x['materiality_flag']=='True'],key=lambda x:int(x['materiality_rank']))[:8]
    b6_status='PASS' if b6t['gate_status']=='PASS' else 'FAIL'; b7_status=b7t['gate_status']; b8_status=b8t['gate_status']; b9_status=b9t['gate_status']
    write(r/'docs/B6_STATUS.md',f'''# B6 Status — Portfolio Overview\n\n- **Gate:** `B6 = FINAL REVIEWED / PASS`\n- **Source:** locked `mart.mart_credit_application_core`\n- **Grain:** one row per granted-loan application/account\n- **Accounts:** {b6['total_accounts']:,}\n- **GOOD / BAD:** {b6['good_accounts']:,} / {b6['bad_accounts']:,}\n- **Observed final-resolution BAD rate:** {pct(b6['observed_bad_rate'])}\n- **Total loan amount proxy:** {money(b6['total_loan_amount'])}\n- **BAD-associated loan amount:** {money(b6['bad_associated_loan_amount'])} ({pct(b6['bad_associated_exposure_share'])})\n- **Tests:** 7/7 PASS\n\nB6 is descriptive. `loan_amnt` is an exposure proxy, not observed EAD; BAD-associated loan amount is not realized loss; the BAD rate is not verified 12-month PD.\n''')
    write(r/'docs/B6_RUN_REPORT.md',f'''# B6 Run Report — Portfolio Overview\n\n## Work completed\n\nB6 profiled the frozen core mart without caps, imputation, outlier treatment, or feature transforms. It produced a portfolio KPI baseline, full numeric percentile profile for `fico_n`, `dti_n`, `revenue`, and `loan_amnt`, and composition tables for purpose, home ownership, employment length, experience and state.\n\n## Results\n\n| Metric | Result |\n|---|---:|\n| Total accounts | {b6['total_accounts']:,} |\n| GOOD | {b6['good_accounts']:,} |\n| BAD | {b6['bad_accounts']:,} |\n| Observed final-resolution BAD rate | {pct(b6['observed_bad_rate'])} |\n| Total `loan_amnt` proxy | {money(b6['total_loan_amount'])} |\n| BAD-associated amount | {money(b6['bad_associated_loan_amount'])} |\n| BAD-associated exposure share | {pct(b6['bad_associated_exposure_share'])} |\n| Issue cohorts | {b6['issue_cohorts']} |\n\n## QA\n\n`{b6t['gate_status']}` across B6T01–B6T07. Category dimensions reconcile to the full core population and 100% of the loan amount proxy. Pricing fields are absent from the core mart; the matched pricing sample remains under the B5 boundary.\n\n## Artifacts\n\n- `outputs/b6/portfolio_kpis.json`\n- `outputs/b6/numeric_profile.csv`\n- `outputs/b6/portfolio_mix.csv`\n- `outputs/b6/b6_test_results.json`\n''')
    write(r/'docs/B7_STATUS.md',f'''# B7 Status — Segment Risk\n\n- **Gate:** `B7 = FINAL REVIEWED / {b7_status}`\n- **Dimensions:** {len(set(x['dimension'] for x in seg))}\n- **Dimensions covered:** `fico_band`, `dti_band`, `revenue_band`, `loan_amount_band`, `purpose`, `home_ownership_n`, `experience_c`, `emp_length`, `addr_state`\n- **Segment rows:** {len(seg):,}, including empty fixed buckets where required\n- **Tests:** 10/10 {b7_status}\n\nB7 reports single-variable descriptive observed BAD segmentation only. It does not select model features or claim predictive performance.\n''')
    headline_md='\n'.join(f"| {x['dimension']} | {x['segment']} | {int(x['accounts']):,} | {pct(x['bad_rate'])} | {float(x['relative_bad_rate']):.2f}x | {pct(x['bad_associated_share'])} |" for x in headline)
    write(r/'docs/B7_RUN_REPORT.md',f'''# B7 Run Report — Segment Risk\n\n## Work completed\n\nB7 segmented the frozen core by the fixed FICO and DTI bands in the plan, exact Q1–Q4 cut points for revenue and loan amount, and the five categorical dimensions. Missing values are explicit as `UNKNOWN / MISSING`; no silent row drops were used. The exact quantile cut points are in `outputs/b7/b7_band_definitions.json`.\n\n## Headline descriptive groups\n\n| Dimension | Segment | Accounts | Observed BAD rate | Relative BAD rate | BAD-associated share |\n|---|---|---:|---:|---:|---:|\n{headline_md}\n\nThese are screening findings, not causal effects, approval rules or automatically approved Block C features.\n\n## QA\n\n`{b7_status}` across B7T01–B7T10. Every dimension reconciles to {b6['total_accounts']:,} accounts and 100% of the loan amount proxy.\n''')
    write(r/'docs/B8_STATUS.md',f'''# B8 Status — Risk Concentration\n\n- **Gate:** `B8 = FINAL REVIEWED / {b8_status}`\n- **Materiality rule:** `relative_bad_rate > 1.0 AND account_share >= 0.001`\n- **Material segments:** {b8['material_segments']}\n- **Ranking key:** BAD-associated loan amount share descending, with deterministic dimension/segment tie-breakers\n- **Tests:** 7/7 {b8_status}\n\nThe primary business measure is BAD-associated exposure share. The project-defined concentration index (`relative_bad_rate × loan_amount_share`) is descriptive only.\n''')
    material_md='\n'.join(f"| {x['materiality_rank']} | {x['dimension']} | {x['segment']} | {int(x['accounts']):,} | {pct(x['bad_rate'])} | {pct(x['bad_associated_share'])} |" for x in material)
    write(r/'docs/B8_RUN_REPORT.md',f'''# B8 Run Report — Risk Concentration\n\n## Work completed\n\nB8 joined elevated observed BAD rates to scale using only B7 single-variable outputs. The materiality rule was fixed before ranking and was not tuned to the observed result. No combinatorial segment search was performed.\n\n## First material rows by BAD-associated exposure share\n\n| Rank | Dimension | Segment | Accounts | Observed BAD rate | BAD-associated share |\n|---:|---|---|---:|---:|---:|\n{material_md}\n\nThe table is a prioritization view for descriptive investigation. It does not represent realized loss, expected loss, a causal driver ranking or a production policy.\n\n## QA\n\n`{b8_status}` across B8T01–B8T07. Account and exposure shares reconcile independently within every dimension, and ranks are deterministic.\n''')
    annual_md='\n'.join(f"| {x['issue_year']} | {int(x['accounts']):,} | {pct(x['bad_rate'])} | {money(x['bad_associated_loan_amount'])} |" for x in annual)
    split_md='\n'.join(f"| {x['split_name']} | {int(x['accounts']):,} | {pct(x['bad_rate'])} | {x['min_issue_d']} → {x['max_issue_d']} |" for x in splits)
    write(r/'docs/B9_STATUS.md',f'''# B9 Status — Vintage / Temporal Analysis\n\n- **Gate:** `B9 = FINAL REVIEWED / {b9_status}`\n- **Temporal authority:** `issue_d`\n- **Monthly cohorts:** {b9['cohorts']}\n- **Annual years:** {b9['years']}\n- **Tests:** 8/8 {b9_status}\n\nMandatory boundary: the 2018 resolved-loan sample is subject to right truncation and resolution selection. A lower observed BAD rate in 2018 is not confirmed credit-quality improvement. This is not live monitoring.\n''')
    write(r/'docs/B9_RUN_REPORT.md',f'''# B9 Run Report — Vintage / Temporal\n\n## Work completed\n\nB9 used `issue_d` as the sole temporal authority and generated monthly cohort, annual cohort and split summaries. Monthly and annual aggregations reconcile exactly to the frozen core.\n\n## Split baseline\n\n| Split | Accounts | Observed BAD rate | Date range |\n|---|---:|---:|---|\n{split_md}\n\n## Annual view\n\n| Issue year | Accounts | Observed BAD rate | BAD-associated amount |\n|---:|---:|---:|---:|\n{annual_md}\n\n## Interpretation boundary\n\nTemporal shifts may be described as associated, coincident or co-moving. They are not treated as causal. The 2018 cohort is a historical shadow/resolved-loan sample and not a live performance-monitoring window.\n''')
    findings='\n'.join(f"- **{x['dimension']} = {x['segment']}**: {pct(x['bad_rate'])} observed BAD rate, {float(x['relative_bad_rate']):.2f}x the portfolio baseline, {pct(x['bad_associated_share'])} of total BAD-associated loan amount." for x in headline[:5])
    write(r/'docs/BLOCK_B_ANALYTICAL_FINDINGS.md',f'''# Block B — Analytical Findings (B6–B9)\n\n## Executive answer\n\nThe resolved granted-loan portfolio contains **{b6['total_accounts']:,} accounts**, with an observed final-resolution BAD rate of **{pct(b6['observed_bad_rate'])}**. BAD-associated `loan_amnt` totals **{money(b6['bad_associated_loan_amount'])}**, or **{pct(b6['bad_associated_exposure_share'])}** of the loan amount proxy.\n\n## Where observed risk is higher\n\n{findings}\n\nThese are descriptive, single-variable comparisons. They are not causal explanations and are not an approval policy.\n\n## Where higher risk overlaps with scale\n\nThe B8 materiality screen found **{b8['material_segments']}** segments under the predefined rule `relative_bad_rate > 1.0 AND account_share >= 0.1%`. The primary prioritization quantity is BAD-associated exposure share; the separate concentration index is project-defined and descriptive.\n\n## How risk moves across cohorts\n\nDevelopment observed BAD rate is **{pct(splits[0]['bad_rate'])}**, Validation **{pct(splits[1]['bad_rate'])}**, OOT **{pct(splits[2]['bad_rate'])}**, and Historical Shadow 2018 **{pct(splits[3]['bad_rate'])}**. The 2018 decrease is not interpreted as confirmed quality improvement because of right truncation/resolution selection.\n\n## Handoff\n\nBlock C may consume the frozen `mart_credit_application_core`. B6–B9 rankings and findings are evidence for analysis, not automatically admitted model features.\n''')
    write(r/'docs/BLOCK_B_ASSUMPTIONS_AND_LIMITS.md',f'''# Block B — Assumptions and Limits\n\n## Metric semantics\n\n- `actual_default` is the observed final-resolution outcome in the governed granting dataset.\n- Observed BAD rate is not verified 12-month PD, forecast PD or model score.\n- `loan_amnt` is an exposure proxy; it is not observed EAD.\n- BAD-associated loan amount is not realized loss, LGD, ECL or expected loss.\n- Matched pricing fields remain B5 descriptive enrichment; they are not blended into the core baseline.\n- Rejected applications remain context-only with no inferred GOOD/BAD outcome.\n\n## Temporal assumptions\n\n- `issue_d` is the only temporal authority.\n- Temporal movement is descriptive and non-causal.\n- The 2018 historical-shadow sample is resolution-selected and right-truncated; it is not live monitoring.\n\n## Scope limits\n\nThis work does not claim ROC-AUC, KS, Gini, calibration, PD, LGD, EAD, ECL, optimized approval policy, reject inference or production monitoring. No caps, imputations, outlier treatments or model transformations were fitted in B6–B9.\n''')
    write(r/'docs/BLOCK_B_FINAL_LOCK.md',f'''# Block B Final Lock\n\n## Status\n\n`BLOCK B = FINAL REVIEWED / LOCKED`\n\n## Locked gates\n\n- B0–B3: FINAL REVIEWED / PASS\n- B4: FINAL REVIEWED / PASS — core application mart\n- B5: FINAL REVIEWED / PASS — controlled enrichment / rejected context boundary\n- B6: FINAL REVIEWED / {b6_status}\n- B7: FINAL REVIEWED / {b7_status}\n- B8: FINAL REVIEWED / {b8_status}\n- B9: FINAL REVIEWED / {b9_status}\n\n## Locked populations\n\n- Core application mart: {b6['total_accounts']:,} accounts; {b6['bad_accounts']:,} BAD; {b6['good_accounts']:,} GOOD; {b6['issue_cohorts']} issue cohorts.\n- Matched pricing sample: 325,255 accounts; B5 bridge authority preserved.\n- Rejected context: 27,648,741 records; context only; no outcome assignment.\n\n## Final claim boundary\n\nAllowed: governed data engineering, data quality, composition, observed BAD segmentation, concentration screening, vintage analysis and descriptive pricing context. Not allowed: verified PD, credit-score model performance, calibration, expected loss, LGD/EAD, optimized approval, causal reject inference or live monitoring.\n\n## Transition\n\n`PORTFOLIO RISK MAPPED. NEXT: BUILD THE MODEL.` Block C consumes the frozen core mart; B6–B9 findings do not silently become model features.\n''')
    ev=r/'evidence/block-b'
    write(ev/'b6-portfolio-overview.md',(r/'docs/B6_RUN_REPORT.md').read_text(encoding='utf-8')+'\n## Evidence files\n\n- `outputs/b6/portfolio_kpis.json`\n- `outputs/b6/numeric_profile.csv`\n- `outputs/b6/portfolio_mix.csv`\n- `outputs/b6/b6_test_results.json`\n')
    write(ev/'b7-segment-risk.md',(r/'docs/B7_RUN_REPORT.md').read_text(encoding='utf-8')+'\n## Evidence files\n\n- `outputs/b7/segment_risk.csv`\n- `outputs/b7/b7_band_definitions.json`\n- `outputs/b7/b7_test_results.json`\n')
    write(ev/'b8-risk-concentration.md',(r/'docs/B8_RUN_REPORT.md').read_text(encoding='utf-8')+'\n## Evidence files\n\n- `outputs/b8/risk_concentration.csv`\n- `outputs/b8/b8_summary.json`\n- `outputs/b8/b8_test_results.json`\n')
    write(ev/'b9-vintage-analysis.md',(r/'docs/B9_RUN_REPORT.md').read_text(encoding='utf-8')+'\n## Evidence files\n\n- `outputs/b9/vintage_monthly.csv`\n- `outputs/b9/vintage_annual.csv`\n- `outputs/b9/vintage_split.csv`\n- `outputs/b9/b9_test_results.json`\n')
    write(ev/'block-b-final-lock.md',(r/'docs/BLOCK_B_FINAL_LOCK.md').read_text(encoding='utf-8'))
    print(json.dumps({'status':'PASS','files':'B6-B9 docs and evidence exported','block_b_status':'FINAL REVIEWED / LOCKED'},indent=2))
    return 0
if __name__=='__main__': raise SystemExit(main())
